sudo: required
services:
  -  docker
before_install: 
  -  docker build -t ssoodehmotaharii/docker-react -f Dockerfile.dev .
script:
  -  docker run -e CI=true ssoodehmotaharii/docker-react npm run test
